/**
 * Agent 5 — Risk Report (Orchestrator)
 * POST / → { token_address, token_symbol? }
 * Runs all 4 agents in parallel and returns a combined risk score.
 */
import { Hono } from 'hono'
import { handle } from 'hono/vercel'
import { readChainlinkFeed } from '../shared/chainlink.js'
import { analyzeOnChain } from '../shared/onchain.js'
import { auditContract } from '../shared/auditor.js'
import { analyzeSentiment } from '../shared/sentiment.js'
import { computeRiskScore, generateSummary } from '../shared/riskScorer.js'
import type { RiskReport } from '../shared/types.js'

const app = new Hono()

app.post('/*', async (c) => {
  let body: Record<string, unknown>
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'Invalid JSON body' }, 400)
  }

  const tokenAddress = (body.token_address as string | undefined)?.trim()
  if (!tokenAddress) {
    return c.json({ error: 'Missing required field: token_address' }, 400)
  }

  if (!/^0x[0-9a-fA-F]{40}$/.test(tokenAddress)) {
    return c.json({ error: 'Invalid token_address — must be a 0x-prefixed 40-char hex address' }, 400)
  }

  const tokenSymbol = (body.token_symbol as string | undefined)?.trim() ?? 'UNKNOWN'

  // Default Chainlink feed from env
  const feedAddress = process.env.CHAINLINK_AVAX_USD_FEED?.trim() ?? ''

  try {
    // Run all 4 agents in parallel (best-effort — failures return null)
    const [chainlinkResult, onchainResult, auditResult, sentimentResult] = await Promise.all([
      feedAddress
        ? readChainlinkFeed(feedAddress, tokenSymbol).catch(() => null)
        : Promise.resolve(null),
      analyzeOnChain(tokenAddress).catch(() => null),
      auditContract(tokenAddress).catch(() => null),
      // Use token symbol + name from onchain result if available (resolved later)
      analyzeSentiment(tokenSymbol, tokenSymbol).catch(() => null),
    ])

    const riskScore = computeRiskScore(chainlinkResult, onchainResult, auditResult, sentimentResult)
    const summary = generateSummary(
      tokenAddress,
      riskScore,
      chainlinkResult,
      onchainResult,
      auditResult,
      sentimentResult,
    )

    const report: RiskReport = {
      token_address: tokenAddress,
      generated_at:  new Date().toISOString(),
      risk_score:    riskScore,
      agents: {
        chainlink: chainlinkResult,
        onchain:   onchainResult,
        audit:     auditResult,
        sentiment: sentimentResult,
      },
      summary,
      disclaimer: 'This report is generated by AI agents and on-chain data. It is not financial advice. Always do your own research.',
    }

    return c.json(report)
  } catch (err) {
    return c.json({ error: `Risk report failed: ${String(err).slice(0, 200)}` }, 500)
  }
})

export const GET = handle(app)
export const POST = handle(app)
